### ISSUE TITLE
meson: ninja install fails with `[Errno 17] File exists`

### ISSUE THREAD

**Issue by madebr** [p11-glue/p11-kit#347]
Hello,

p11-kit version: 0.23.22 source release
meson version: 0.56.0
ninja version: 0.10.1

When using the meson build system to build p11-kit on Linux,
`ninja install -v` fails with the following log.
```
$ ninja install -v
[0/1] /usr/bin/python3 /home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/meson.py install --no-rebuild
Installing p11-kit/libp11-kit.so.0.3.0 to /home/maarten/.conan/data/p11-kit/0.23.22/_/_/package/5e56dd351b111e9b0af7bea144db8f0e2eda43d9/lib
Installing p11-kit/p11-kit-client.so to /home/maarten/.conan/data/p11-kit/0.23.22/_/_/package/5e56dd351b111e9b0af7bea144db8f0e2eda43d9/lib/pkcs11
Installing p11-kit/p11-kit to /home/maarten/.conan/data/p11-kit/0.23.22/_/_/package/5e56dd351b111e9b0af7bea144db8f0e2eda43d9/bin
Traceback (most recent call last):
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/mesonmain.py", line 140, in run
    return options.run_func(options)
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/minstall.py", line 554, in run
    installer.do_install(datafilename)
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/minstall.py", line 372, in do_install
    self.install_targets(d)
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/minstall.py", line 482, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(d.dirmaker, outdir))
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/minstall.py", line 266, in do_copyfile
    dirmaker.makedirs(outdir, exist_ok=True)
  File "/home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/mesonbuild/minstall.py", line 63, in makedirs
    os.makedirs(path, exist_ok=exist_ok)
  File "/usr/lib64/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/maarten/.conan/data/p11-kit/0.23.22/_/_/package/5e56dd351b111e9b0af7bea144db8f0e2eda43d9/bin/p11-kit'
FAILED: meson-install 
/usr/bin/python3 /home/maarten/.conan/data/meson/0.56.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/bin/meson.py install --no-rebuild
ninja: build stopped: subcommand failed.`
```

**Comment by ueno** [comment]
It looks strange that Python's `os.makedirs(path, exist_ok=True)` throws an exception despite the documentation; perhaps a race condition? Does it happen with `ninja -j 1 install` as well?

**Comment by madebr** [comment]
Yes, running `ninja install -j1` shows the same error.
Here is the complete build log: [log.txt](https://github.com/p11-glue/p11-kit/files/5749575/log.txt)
The driver is conan.

This is the state of the install prefix after the failed install:
```
5e56dd351b111e9b0af7bea144db8f0e2eda43d9
├── bin
│   └── p11-kit
└── lib
    ├── libp11-kit.so -> libp11-kit.so.0
    ├── libp11-kit.so.0 -> libp11-kit.so.0.3.0
    ├── libp11-kit.so.0.3.0
    └── pkcs11
        └── p11-kit-client.so
```

**Comment by madebr** [comment]
I compared my log with the log from `.travis.yml`, and I found the problem:
conan sets the `libexec` folder to `bin`.
Because this is the same as the bindir, the second `os.mkdirs` fails.
Manually setting `libexecdir` to another folder makes the error go away.
