### ISSUE TITLE
OSError and SegFault encountered when building p11-Kit against 32 bit Python using 64 bit time flags

### ISSUE THREAD

**Issue by TabLand** [p11-glue/p11-kit#507]
Hi Team,

Not sure if this is the right place to log this issue (perhaps this resides better as an issue in cpython), if not - perhaps helpful just for awareness. I followed the instructions for Linux From Scratch (LFS) book version 11.3, which builds `p11-kit-0.24.1` using the following dependencies:

```
python-3.11.2
meson-1.1.0
```
Most of the (userspace) packages have been build with the following 64-bit flags...
```
CPPFLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64"
```
... with the exception of the below packages:
```
binutils-2.40 (build fails, requires further investigation)
gcc-12.2.0 (not required)
grub-2.06 (LFS instructions explicitly advised not to)
linux-6.1.11 (not required)
```
The following error is encountered:
```
ijtaba@lfs:/sources/p11-kit-0.24.1$ mkdir p11-build && cd p11-build && meson --prefix=/usr --buildtype=release \ 
  -Dtrust_paths=/etc/pki/anchors && ninja
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mesonbuild/mesonmain.py", line 193, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 309, in run
    app.generate()
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 186, in generate
    self._generate(env)
  File "/usr/lib/python3.11/site-packages/mesonbuild/msetup.py", line 194, in _generate
    mlog.debug('Build started at', datetime.datetime.now().isoformat())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 75] Value too large for defined data type

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
Segmentation fault

```

**Comment by ueno** [comment]
Does `python -c 'import datetime; print(datetime.datetime.now())'` work? If not I would say it's an issue in your setup rather than of p11-kit.
